// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pelanggan.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	pelanggan.proto

It has these top-level messages:
	AddPelangganReq
	ReadByNamaPelangganReq
	ReadByNamaPelangganResp
	ReadByKeteranganResp
	ReadByKeteranganReq
	ReadPelangganResp
	UpdatePelangganReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddPelangganReq struct {
	NamaPelanggan string `protobuf:"bytes,1,opt,name=namaPelanggan" json:"namaPelanggan,omitempty"`
	Telepon       string `protobuf:"bytes,2,opt,name=telepon" json:"telepon,omitempty"`
	Email         string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Status        int32  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	CreatedBy     string `protobuf:"bytes,5,opt,name=createdBy" json:"createdBy,omitempty"`
	Keterangan    string `protobuf:"bytes,6,opt,name=keterangan" json:"keterangan,omitempty"`
}

func (m *AddPelangganReq) Reset()                    { *m = AddPelangganReq{} }
func (m *AddPelangganReq) String() string            { return proto.CompactTextString(m) }
func (*AddPelangganReq) ProtoMessage()               {}
func (*AddPelangganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddPelangganReq) GetNamaPelanggan() string {
	if m != nil {
		return m.NamaPelanggan
	}
	return ""
}

func (m *AddPelangganReq) GetTelepon() string {
	if m != nil {
		return m.Telepon
	}
	return ""
}

func (m *AddPelangganReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddPelangganReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddPelangganReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddPelangganReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadByNamaPelangganReq struct {
	NamaPelanggan string `protobuf:"bytes,1,opt,name=namaPelanggan" json:"namaPelanggan,omitempty"`
}

func (m *ReadByNamaPelangganReq) Reset()                    { *m = ReadByNamaPelangganReq{} }
func (m *ReadByNamaPelangganReq) String() string            { return proto.CompactTextString(m) }
func (*ReadByNamaPelangganReq) ProtoMessage()               {}
func (*ReadByNamaPelangganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadByNamaPelangganReq) GetNamaPelanggan() string {
	if m != nil {
		return m.NamaPelanggan
	}
	return ""
}

type ReadByNamaPelangganResp struct {
	IDPelanggan   int32  `protobuf:"varint,1,opt,name=IDPelanggan" json:"IDPelanggan,omitempty"`
	NamaPelanggan string `protobuf:"bytes,2,opt,name=namaPelanggan" json:"namaPelanggan,omitempty"`
	Telepon       string `protobuf:"bytes,3,opt,name=telepon" json:"telepon,omitempty"`
	Email         string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Status        int32  `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	CreatedBy     string `protobuf:"bytes,6,opt,name=createdBy" json:"createdBy,omitempty"`
	Keterangan    string `protobuf:"bytes,7,opt,name=keterangan" json:"keterangan,omitempty"`
}

func (m *ReadByNamaPelangganResp) Reset()                    { *m = ReadByNamaPelangganResp{} }
func (m *ReadByNamaPelangganResp) String() string            { return proto.CompactTextString(m) }
func (*ReadByNamaPelangganResp) ProtoMessage()               {}
func (*ReadByNamaPelangganResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadByNamaPelangganResp) GetIDPelanggan() int32 {
	if m != nil {
		return m.IDPelanggan
	}
	return 0
}

func (m *ReadByNamaPelangganResp) GetNamaPelanggan() string {
	if m != nil {
		return m.NamaPelanggan
	}
	return ""
}

func (m *ReadByNamaPelangganResp) GetTelepon() string {
	if m != nil {
		return m.Telepon
	}
	return ""
}

func (m *ReadByNamaPelangganResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReadByNamaPelangganResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadByNamaPelangganResp) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadByNamaPelangganResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadByKeteranganResp struct {
	AllKeterangan []*ReadByNamaPelangganResp `protobuf:"bytes,1,rep,name=allKeterangan" json:"allKeterangan,omitempty"`
}

func (m *ReadByKeteranganResp) Reset()                    { *m = ReadByKeteranganResp{} }
func (m *ReadByKeteranganResp) String() string            { return proto.CompactTextString(m) }
func (*ReadByKeteranganResp) ProtoMessage()               {}
func (*ReadByKeteranganResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadByKeteranganResp) GetAllKeterangan() []*ReadByNamaPelangganResp {
	if m != nil {
		return m.AllKeterangan
	}
	return nil
}

type ReadByKeteranganReq struct {
	IDPelanggan   int32  `protobuf:"varint,1,opt,name=IDPelanggan" json:"IDPelanggan,omitempty"`
	NamaPelanggan string `protobuf:"bytes,2,opt,name=namaPelanggan" json:"namaPelanggan,omitempty"`
	Telepon       string `protobuf:"bytes,3,opt,name=telepon" json:"telepon,omitempty"`
	Email         string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Status        int32  `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	CreatedBy     string `protobuf:"bytes,6,opt,name=createdBy" json:"createdBy,omitempty"`
	Keterangan    string `protobuf:"bytes,7,opt,name=keterangan" json:"keterangan,omitempty"`
}

func (m *ReadByKeteranganReq) Reset()                    { *m = ReadByKeteranganReq{} }
func (m *ReadByKeteranganReq) String() string            { return proto.CompactTextString(m) }
func (*ReadByKeteranganReq) ProtoMessage()               {}
func (*ReadByKeteranganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadByKeteranganReq) GetIDPelanggan() int32 {
	if m != nil {
		return m.IDPelanggan
	}
	return 0
}

func (m *ReadByKeteranganReq) GetNamaPelanggan() string {
	if m != nil {
		return m.NamaPelanggan
	}
	return ""
}

func (m *ReadByKeteranganReq) GetTelepon() string {
	if m != nil {
		return m.Telepon
	}
	return ""
}

func (m *ReadByKeteranganReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReadByKeteranganReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadByKeteranganReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadByKeteranganReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadPelangganResp struct {
	AllPelanggan []*ReadByNamaPelangganResp `protobuf:"bytes,1,rep,name=allPelanggan" json:"allPelanggan,omitempty"`
}

func (m *ReadPelangganResp) Reset()                    { *m = ReadPelangganResp{} }
func (m *ReadPelangganResp) String() string            { return proto.CompactTextString(m) }
func (*ReadPelangganResp) ProtoMessage()               {}
func (*ReadPelangganResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadPelangganResp) GetAllPelanggan() []*ReadByNamaPelangganResp {
	if m != nil {
		return m.AllPelanggan
	}
	return nil
}

type UpdatePelangganReq struct {
	IDPelanggan   int32  `protobuf:"varint,1,opt,name=IDPelanggan" json:"IDPelanggan,omitempty"`
	NamaPelanggan string `protobuf:"bytes,2,opt,name=namaPelanggan" json:"namaPelanggan,omitempty"`
	Telepon       string `protobuf:"bytes,3,opt,name=telepon" json:"telepon,omitempty"`
	Email         string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Status        int32  `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	UpdateBy      string `protobuf:"bytes,6,opt,name=updateBy" json:"updateBy,omitempty"`
	Keterangan    string `protobuf:"bytes,7,opt,name=keterangan" json:"keterangan,omitempty"`
}

func (m *UpdatePelangganReq) Reset()                    { *m = UpdatePelangganReq{} }
func (m *UpdatePelangganReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePelangganReq) ProtoMessage()               {}
func (*UpdatePelangganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdatePelangganReq) GetIDPelanggan() int32 {
	if m != nil {
		return m.IDPelanggan
	}
	return 0
}

func (m *UpdatePelangganReq) GetNamaPelanggan() string {
	if m != nil {
		return m.NamaPelanggan
	}
	return ""
}

func (m *UpdatePelangganReq) GetTelepon() string {
	if m != nil {
		return m.Telepon
	}
	return ""
}

func (m *UpdatePelangganReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdatePelangganReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdatePelangganReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *UpdatePelangganReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func init() {
	proto.RegisterType((*AddPelangganReq)(nil), "grpc.AddPelangganReq")
	proto.RegisterType((*ReadByNamaPelangganReq)(nil), "grpc.ReadByNamaPelangganReq")
	proto.RegisterType((*ReadByNamaPelangganResp)(nil), "grpc.ReadByNamaPelangganResp")
	proto.RegisterType((*ReadByKeteranganResp)(nil), "grpc.ReadByKeteranganResp")
	proto.RegisterType((*ReadByKeteranganReq)(nil), "grpc.ReadByKeteranganReq")
	proto.RegisterType((*ReadPelangganResp)(nil), "grpc.ReadPelangganResp")
	proto.RegisterType((*UpdatePelangganReq)(nil), "grpc.UpdatePelangganReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for PelangganService service

type PelangganServiceClient interface {
	AddPelanggan(ctx context.Context, in *AddPelangganReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadByNamaPelanggan(ctx context.Context, in *ReadByNamaPelangganReq, opts ...grpc1.CallOption) (*ReadByNamaPelangganResp, error)
	ReadPelanggan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadPelangganResp, error)
	UpdatePelanggan(ctx context.Context, in *UpdatePelangganReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadByKeterangan(ctx context.Context, in *ReadByKeteranganReq, opts ...grpc1.CallOption) (*ReadByKeteranganResp, error)
}

type pelangganServiceClient struct {
	cc *grpc1.ClientConn
}

func NewPelangganServiceClient(cc *grpc1.ClientConn) PelangganServiceClient {
	return &pelangganServiceClient{cc}
}

func (c *pelangganServiceClient) AddPelanggan(ctx context.Context, in *AddPelangganReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.PelangganService/AddPelanggan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pelangganServiceClient) ReadByNamaPelanggan(ctx context.Context, in *ReadByNamaPelangganReq, opts ...grpc1.CallOption) (*ReadByNamaPelangganResp, error) {
	out := new(ReadByNamaPelangganResp)
	err := grpc1.Invoke(ctx, "/grpc.PelangganService/ReadByNamaPelanggan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pelangganServiceClient) ReadPelanggan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadPelangganResp, error) {
	out := new(ReadPelangganResp)
	err := grpc1.Invoke(ctx, "/grpc.PelangganService/ReadPelanggan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pelangganServiceClient) UpdatePelanggan(ctx context.Context, in *UpdatePelangganReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.PelangganService/UpdatePelanggan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pelangganServiceClient) ReadByKeterangan(ctx context.Context, in *ReadByKeteranganReq, opts ...grpc1.CallOption) (*ReadByKeteranganResp, error) {
	out := new(ReadByKeteranganResp)
	err := grpc1.Invoke(ctx, "/grpc.PelangganService/ReadByKeterangan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PelangganService service

type PelangganServiceServer interface {
	AddPelanggan(context.Context, *AddPelangganReq) (*google_protobuf.Empty, error)
	ReadByNamaPelanggan(context.Context, *ReadByNamaPelangganReq) (*ReadByNamaPelangganResp, error)
	ReadPelanggan(context.Context, *google_protobuf.Empty) (*ReadPelangganResp, error)
	UpdatePelanggan(context.Context, *UpdatePelangganReq) (*google_protobuf.Empty, error)
	ReadByKeterangan(context.Context, *ReadByKeteranganReq) (*ReadByKeteranganResp, error)
}

func RegisterPelangganServiceServer(s *grpc1.Server, srv PelangganServiceServer) {
	s.RegisterService(&_PelangganService_serviceDesc, srv)
}

func _PelangganService_AddPelanggan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPelangganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PelangganServiceServer).AddPelanggan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PelangganService/AddPelanggan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PelangganServiceServer).AddPelanggan(ctx, req.(*AddPelangganReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PelangganService_ReadByNamaPelanggan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadByNamaPelangganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PelangganServiceServer).ReadByNamaPelanggan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PelangganService/ReadByNamaPelanggan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PelangganServiceServer).ReadByNamaPelanggan(ctx, req.(*ReadByNamaPelangganReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PelangganService_ReadPelanggan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PelangganServiceServer).ReadPelanggan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PelangganService/ReadPelanggan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PelangganServiceServer).ReadPelanggan(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PelangganService_UpdatePelanggan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePelangganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PelangganServiceServer).UpdatePelanggan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PelangganService/UpdatePelanggan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PelangganServiceServer).UpdatePelanggan(ctx, req.(*UpdatePelangganReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PelangganService_ReadByKeterangan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadByKeteranganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PelangganServiceServer).ReadByKeterangan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PelangganService/ReadByKeterangan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PelangganServiceServer).ReadByKeterangan(ctx, req.(*ReadByKeteranganReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PelangganService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.PelangganService",
	HandlerType: (*PelangganServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddPelanggan",
			Handler:    _PelangganService_AddPelanggan_Handler,
		},
		{
			MethodName: "ReadByNamaPelanggan",
			Handler:    _PelangganService_ReadByNamaPelanggan_Handler,
		},
		{
			MethodName: "ReadPelanggan",
			Handler:    _PelangganService_ReadPelanggan_Handler,
		},
		{
			MethodName: "UpdatePelanggan",
			Handler:    _PelangganService_UpdatePelanggan_Handler,
		},
		{
			MethodName: "ReadByKeterangan",
			Handler:    _PelangganService_ReadByKeterangan_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "pelanggan.proto",
}

func init() { proto.RegisterFile("pelanggan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xbb, 0x75, 0xec, 0xd2, 0x69, 0xa3, 0x94, 0xa1, 0xa4, 0x8b, 0x29, 0xc8, 0xb2, 0x38,
	0xe4, 0xe4, 0x4a, 0xe5, 0x0e, 0x6a, 0xa0, 0x07, 0x54, 0x09, 0x21, 0xf3, 0xe7, 0xc2, 0x69, 0x13,
	0x2f, 0x56, 0xc4, 0xc6, 0x76, 0x9c, 0x0d, 0x52, 0x8e, 0x3c, 0x18, 0xef, 0x82, 0xc4, 0x81, 0xd7,
	0x40, 0x5e, 0x63, 0xc7, 0x6b, 0xc7, 0x4e, 0x8e, 0x88, 0xe3, 0x7e, 0xeb, 0x19, 0x7f, 0xf3, 0x9b,
	0xd9, 0x81, 0x41, 0xc2, 0x05, 0x8b, 0xc2, 0x90, 0x45, 0x5e, 0x92, 0xc6, 0x32, 0xc6, 0x5e, 0x98,
	0x26, 0x53, 0xfb, 0x71, 0x18, 0xc7, 0xa1, 0xe0, 0x57, 0x4a, 0x9b, 0xac, 0xbe, 0x5c, 0xf1, 0x79,
	0x22, 0xd7, 0xf9, 0x27, 0xee, 0x0f, 0x02, 0x83, 0x9b, 0x20, 0x78, 0x57, 0x44, 0xfa, 0x7c, 0x81,
	0xcf, 0xa0, 0x1f, 0xb1, 0x39, 0x2b, 0x35, 0x4a, 0x1c, 0x32, 0x3a, 0xf6, 0x75, 0x11, 0x29, 0x1c,
	0x49, 0x2e, 0x78, 0x12, 0x47, 0xf4, 0x50, 0xdd, 0x17, 0x47, 0x3c, 0x07, 0x93, 0xcf, 0xd9, 0x4c,
	0x50, 0x43, 0xe9, 0xf9, 0x01, 0x87, 0x60, 0x2d, 0x25, 0x93, 0xab, 0x25, 0xed, 0x39, 0x64, 0x64,
	0xfa, 0x7f, 0x4f, 0x78, 0x09, 0xc7, 0xd3, 0x94, 0x33, 0xc9, 0x83, 0xf1, 0x9a, 0x9a, 0x2a, 0x62,
	0x23, 0xe0, 0x53, 0x80, 0xaf, 0x5c, 0xf2, 0x94, 0x45, 0x99, 0x11, 0x4b, 0x5d, 0x57, 0x14, 0xf7,
	0x05, 0x0c, 0x7d, 0xce, 0x82, 0xf1, 0xfa, 0x6d, 0xd5, 0xdc, 0xde, 0x55, 0xb8, 0xbf, 0x09, 0x5c,
	0x6c, 0x4d, 0xb0, 0x4c, 0xd0, 0x81, 0x93, 0x37, 0xaf, 0xf5, 0x78, 0xd3, 0xaf, 0x4a, 0xcd, 0x7f,
	0x1c, 0xee, 0x20, 0x65, 0xb4, 0x90, 0xea, 0x6d, 0x27, 0x65, 0xb6, 0x93, 0xb2, 0xba, 0x49, 0x1d,
	0x35, 0x48, 0x7d, 0x86, 0xf3, 0xbc, 0xd0, 0xbb, 0x52, 0x53, 0x55, 0xbe, 0x82, 0x3e, 0x13, 0x62,
	0x23, 0x52, 0xe2, 0x18, 0xa3, 0x93, 0xeb, 0x27, 0x5e, 0x36, 0x3c, 0x5e, 0x0b, 0x1b, 0x5f, 0x8f,
	0x71, 0x7f, 0x11, 0x78, 0xd0, 0xcc, 0xbe, 0xf8, 0xcf, 0x10, 0x7e, 0x82, 0xfb, 0x59, 0x91, 0xfa,
	0x94, 0xdc, 0xc0, 0x29, 0x13, 0xa2, 0x5a, 0xe3, 0x1e, 0xf8, 0xb4, 0x10, 0xf7, 0x27, 0x01, 0xfc,
	0x98, 0x04, 0x4c, 0x72, 0x6d, 0x82, 0xff, 0x35, 0x78, 0x36, 0xdc, 0x5b, 0x29, 0x97, 0x25, 0xbb,
	0xf2, 0xbc, 0x0b, 0xdd, 0xf5, 0x77, 0x03, 0xce, 0x4a, 0x47, 0xef, 0x79, 0xfa, 0x6d, 0x36, 0xe5,
	0xf8, 0x12, 0x4e, 0xab, 0xbb, 0x07, 0x1f, 0xe6, 0xd0, 0x6a, 0xfb, 0xc8, 0x1e, 0x7a, 0xf9, 0x06,
	0xf3, 0x8a, 0x0d, 0xe6, 0xdd, 0x66, 0x1b, 0xcc, 0x3d, 0xc0, 0x0f, 0xc5, 0xd4, 0x69, 0x84, 0xf1,
	0xb2, 0x03, 0xfe, 0xc2, 0xee, 0x6e, 0x8d, 0x7b, 0x80, 0x63, 0xe8, 0x6b, 0x6d, 0xc6, 0x16, 0x03,
	0xf6, 0xc5, 0x26, 0x53, 0x3d, 0xc7, 0x2d, 0x0c, 0x6a, 0x1d, 0x45, 0x9a, 0x7f, 0xdd, 0x6c, 0x74,
	0x47, 0x81, 0x77, 0x70, 0x56, 0x7f, 0x56, 0xf8, 0xa8, 0xea, 0x5f, 0x7b, 0x6e, 0xb6, 0xdd, 0x76,
	0x95, 0x79, 0x9a, 0x58, 0x2a, 0xfd, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0xdb, 0x17,
	0x10, 0x28, 0x06, 0x00, 0x00,
}
